"""Generates a clean, professional PDF report from an earnings summary dict using fpdf2."""

from fpdf import FPDF
from fpdf.enums import XPos, YPos

_UNICODE_MAP = str.maketrans({
    "–": "-",   # en-dash
    "—": "--",  # em-dash
    "‘": "'",   # left single quote
    "’": "'",   # right single quote
    "“": '"',   # left double quote
    "”": '"',   # right double quote
    "…": "...", # ellipsis
    "•": "-",   # bullet
    "·": "-",   # middle dot
})

_C_GREEN  = (22, 163, 74)
_C_RED    = (220, 38, 38)
_C_BLUE   = (37, 99, 235)
_C_AMBER  = (217, 119, 6)
_C_DARK   = (30, 30, 30)
_C_MID    = (80, 80, 80)
_C_LIGHT  = (150, 150, 150)
_C_RULE   = (220, 220, 220)
_C_SURF   = (245, 245, 245)

_SECTION_COLORS = {
    "Financial Highlights":     _C_BLUE,
    "Key Positives":            _C_GREEN,
    "Key Risks":                _C_RED,
    "Forward Guidance":         _C_AMBER,
    "Notable Analyst Questions": _C_AMBER,
}


def _safe(text: str) -> str:
    return str(text).translate(_UNICODE_MAP).encode("latin-1", errors="replace").decode("latin-1")


def _text_height(pdf: FPDF, text: str, width: float, line_h: float = 6.0) -> float:
    """Estimate rendered height by counting word-wrapped lines at current font."""
    words = text.split()
    lines, current = [], ""
    for word in words:
        test = (current + " " + word).strip()
        if pdf.get_string_width(test) <= width:
            current = test
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return max(1, len(lines)) * line_h


class _PDF(FPDF):
    def footer(self) -> None:
        self.set_y(-14)
        self.set_draw_color(*_C_RULE)
        self.set_line_width(0.2)
        rule_y = self.get_y() - 2
        self.line(self.l_margin, rule_y, self.w - self.r_margin, rule_y)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*_C_LIGHT)
        col = (self.w - self.l_margin - self.r_margin) / 3
        self.cell(col, 8, "", new_x=XPos.RIGHT)
        self.cell(col, 8, f"Page {self.page_no()}", align="C", new_x=XPos.RIGHT)
        self.cell(col, 8, "Generated by Earnings.AI", align="R")


def _hr(pdf: FPDF) -> None:
    pdf.set_draw_color(*_C_RULE)
    pdf.set_line_width(0.3)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())


def _header_block(pdf: FPDF, company: str, quarter: str, date: str) -> None:
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*_C_DARK)
    pdf.cell(0, 10, _safe(company), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_C_LIGHT)
    pdf.cell(0, 6, _safe(f"{quarter}   |   {date}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(5)
    _hr(pdf)
    pdf.ln(10)


def _scorecard(pdf: FPDF, sentiment: str, score, direction: str) -> None:
    lm = pdf.l_margin
    full_w = pdf.w - lm - pdf.r_margin
    gap = 5
    box_w = (full_w - 2 * gap) / 3
    box_h = 24
    y = pdf.get_y()

    sentiment_color = (
        _C_GREEN if sentiment == "Bullish" else
        _C_RED   if sentiment == "Bearish" else
        _C_LIGHT
    )
    direction_color = (
        _C_BLUE  if direction == "Raised"  else
        _C_RED   if direction == "Lowered" else
        _C_LIGHT
    )

    boxes = [
        ("SENTIMENT",        _safe(str(sentiment)),        sentiment_color),
        ("CONFIDENCE SCORE", _safe(f"{score}/10"),         _C_DARK),
        ("GUIDANCE",         _safe(str(direction)),        direction_color),
    ]

    for i, (label, value, color) in enumerate(boxes):
        x = lm + i * (box_w + gap)
        pdf.set_fill_color(*_C_SURF)
        pdf.set_draw_color(*_C_RULE)
        pdf.set_line_width(0.3)
        pdf.rect(x, y, box_w, box_h, style="FD")
        # Label
        pdf.set_xy(x + 5, y + 5)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*_C_LIGHT)
        pdf.cell(box_w - 10, 4, label)
        # Value
        pdf.set_xy(x + 5, y + 12)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*color)
        pdf.cell(box_w - 10, 8, value)

    pdf.set_y(y + box_h + 10)
    pdf.set_text_color(*_C_DARK)


def _verdict_box(pdf: FPDF, verdict: str) -> None:
    lm = pdf.l_margin
    full_w = pdf.w - lm - pdf.r_margin
    pad_left, pad_v = 10, 6
    text_w = full_w - pad_left - 6

    pdf.set_font("Helvetica", "I", 10)
    safe_v = _safe(f'"{verdict}"')
    content_h = _text_height(pdf, safe_v, text_w)
    box_h = content_h + pad_v * 2

    y = pdf.get_y()
    # Gray background
    pdf.set_fill_color(*_C_SURF)
    pdf.rect(lm, y, full_w, box_h, style="F")
    # Green left accent bar
    pdf.set_fill_color(*_C_GREEN)
    pdf.rect(lm, y, 3, box_h, style="F")
    # Italic verdict text
    pdf.set_xy(lm + pad_left, y + pad_v)
    pdf.set_text_color(*_C_MID)
    pdf.multi_cell(text_w, 6, safe_v, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_y(y + box_h + 10)
    pdf.set_text_color(*_C_DARK)


def _section_header(pdf: FPDF, title: str) -> None:
    color = _SECTION_COLORS.get(title, _C_LIGHT)
    lm = pdf.l_margin
    y = pdf.get_y()
    bar_h = 12
    # Colored left accent bar
    pdf.set_fill_color(*color)
    pdf.rect(lm, y, 3, bar_h, style="F")
    # Title text
    pdf.set_xy(lm + 7, y + 1)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*_C_DARK)
    pdf.cell(0, 10, _safe(title.upper()), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)


def _bullet_list(pdf: FPDF, items: list[str]) -> None:
    lm = pdf.l_margin
    bullet_x = lm + 5
    text_x = lm + 14
    text_w = pdf.w - text_x - pdf.r_margin

    # Set left margin so wrapped lines align with the text indent
    pdf.set_left_margin(text_x)

    for item in items:
        y = pdf.get_y()
        pdf.set_xy(bullet_x, y)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*_C_LIGHT)
        pdf.cell(9, 6, "-")
        pdf.set_xy(text_x, y)
        pdf.set_text_color(*_C_MID)
        pdf.multi_cell(text_w, 6, _safe(item), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_left_margin(lm)
    pdf.ln(3)


def _body_text(pdf: FPDF, text: str) -> None:
    lm = pdf.l_margin
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_C_MID)
    pdf.set_x(lm + 5)
    pdf.multi_cell(pdf.w - lm - pdf.r_margin - 5, 6,
                   _safe(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)


def export_pdf(summary: dict) -> bytes:
    """Convert a structured earnings summary dict into a formatted PDF.

    Args:
        summary: Dict produced by summarize_transcript().

    Returns:
        PDF file contents as raw bytes.
    """
    pdf = _PDF()
    pdf.set_margins(left=18, top=18, right=18)
    pdf.set_auto_page_break(auto=True, margin=22)
    pdf.add_page()

    _header_block(
        pdf,
        summary.get("company_name", "Unknown Company"),
        summary.get("quarter", ""),
        summary.get("date", ""),
    )

    _scorecard(
        pdf,
        summary.get("sentiment", "-"),
        summary.get("management_confidence_score", "-"),
        summary.get("guidance_direction", "-"),
    )

    _verdict_box(pdf, summary.get("verdict", ""))

    sections = [
        ("Financial Highlights",      summary.get("financial_highlights", []),      "list"),
        ("Key Positives",             summary.get("key_positives", []),              "list"),
        ("Key Risks",                 summary.get("key_risks", []),                  "list"),
        ("Forward Guidance",          summary.get("forward_guidance", ""),           "text"),
        ("Notable Analyst Questions", summary.get("notable_analyst_questions", []), "list"),
    ]

    for title, content, kind in sections:
        pdf.ln(4)
        _section_header(pdf, title)
        if kind == "list":
            _bullet_list(pdf, content)
        else:
            _body_text(pdf, content)

    return bytes(pdf.output())
